Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Cocktail.create(name: "mojito")
Cocktail.create(name: "Bloody Mary")
Cocktail.create(name: "Sex on the beach")
